# Generated by Django 4.1.1 on 2022-09-14 17:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('u_username', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True, verbose_name='Usuario')),
                ('password', models.CharField(max_length=256, verbose_name='Contraseña')),
                ('u_perfil', models.CharField(max_length=20, verbose_name='Perfil usuario')),
                ('u_nombres', models.CharField(max_length=20, verbose_name='Nombres usuario')),
                ('u_apellidos', models.CharField(max_length=20, verbose_name='Apellidos usuario')),
                ('u_telefono', models.CharField(max_length=15, verbose_name='Teléfono usuario')),
                ('u_genero', models.CharField(max_length=1, null=True, verbose_name='Genero usuario')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID paciente')),
                ('p_fecha_nacimiento', models.DateField(verbose_name='Fecha nacimiento paciente')),
                ('p_ciudad', models.CharField(max_length=20, verbose_name='Ciudad paciente')),
                ('p_direccion', models.CharField(max_length=40, verbose_name='Direccion paciente')),
                ('p_latitud', models.CharField(max_length=15, null=True, verbose_name='Latitud paciente')),
                ('p_longitud', models.CharField(max_length=15, null=True, verbose_name='Longitud paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Signos_Vitales',
            fields=[
                ('sv_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID signos vitales')),
                ('sv_fecha_hora', models.DateTimeField(auto_now=True, verbose_name='Fecha hora signos vitales')),
                ('sv_oximetria', models.FloatField(null=True, verbose_name='Oximetría')),
                ('sv_f_respiratoria', models.FloatField(null=True, verbose_name='Frecuencia respiratoria')),
                ('sv_f_cardiaca', models.FloatField(null=True, verbose_name='Frecuencia cardíaca')),
                ('sv_temperatura', models.FloatField(null=True, verbose_name='Temperatura')),
                ('sv_presion_arterial', models.FloatField(null=True, verbose_name='Presión arterial')),
                ('sv_glicemia', models.FloatField(null=True, verbose_name='Glicemia')),
                ('sv_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signos_vitales', to='authApp.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Personal_Salud',
            fields=[
                ('ps_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID personal salud')),
                ('ps_rol', models.CharField(max_length=20, verbose_name='Rol personal salud')),
                ('ps_especialidad', models.CharField(max_length=40, verbose_name='Especialidad personal salud')),
                ('ps_username', models.ForeignKey(max_length=30, on_delete=django.db.models.deletion.CASCADE, related_name='personal_salud', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='paciente',
            name='p_personal_salud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paciente', to='authApp.personal_salud'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='p_username',
            field=models.ForeignKey(max_length=30, on_delete=django.db.models.deletion.CASCADE, related_name='paciente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Historia_Clinica',
            fields=[
                ('hc_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID historia clínica')),
                ('hc_fecha_hora', models.DateTimeField(auto_now=True, verbose_name='Fecha hora historia clínica')),
                ('hc_entorno', models.CharField(max_length=50, verbose_name='Entorno')),
                ('hc_diagnostico', models.CharField(max_length=100, verbose_name='Diagnóstico')),
                ('hc_recomendaciones', models.CharField(max_length=200, verbose_name='Recomendaciones')),
                ('hc_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historia_clinica', to='authApp.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Familiar',
            fields=[
                ('f_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID familiar')),
                ('f_correo', models.EmailField(max_length=50, unique=True, verbose_name='Correo familiar')),
                ('f_parentesco', models.CharField(max_length=20, verbose_name='Parentesco familiar')),
                ('f_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='familiar', to='authApp.paciente')),
                ('f_username', models.ForeignKey(max_length=30, on_delete=django.db.models.deletion.CASCADE, related_name='familiar', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
